### ISSUE TITLE
'Parameter is not valid' when drawing to bitmap

### ISSUE THREAD

**Issue by mcrawford-fms** [svg-net/SVG#1004]
#### Description
I'm working with an app that produces svg files and I'm attempting to convert those svgs to jpg by using your library to draw them to a Bitmap, then save as jpg.  All of the svgs (that I've tried so far) produced by the app fail to draw with the exception below.  The svgs are fine in the sense that the load and display without issue in Inkscape and browsers.  The app that produces them has been used in production for many years (AFAIK) with no complaints about invalid or corrupted images.  Any idea what the problem is?  I'm really not sure if it's an issue with the image or the library, and the error is so generic that it's impossible to google.

```
Unhandled exception. System.ArgumentException: Parameter is not valid.
   at System.Drawing.SafeNativeMethods.Gdip.CheckStatus(Int32 status)
   at System.Drawing.Graphics.ScaleTransform(Single sx, Single sy, MatrixOrder order)
   at Svg.SvgRenderer.ScaleTransform(Single sx, Single sy, MatrixOrder order)
   at Svg.SvgViewBox.AddViewBoxTransform(SvgAspectRatio aspectRatio, ISvgRenderer renderer, SvgFragment frag)
   at Svg.SvgFragment.PushTransforms(ISvgRenderer renderer)
   at Svg.SvgElement.Render(ISvgRenderer renderer)
   at Svg.SvgFragment.Render(ISvgRenderer renderer)
   at Svg.SvgDocument.Draw(ISvgRenderer renderer, ISvgBoundable boundable)
   at Svg.SvgDocument.Draw(Graphics graphics, Nullable`1 size)
   at Svg.SvgDocument.Draw(Graphics graphics)
   at Program.<Main>$(String[] args) 
```

#### Example data
[Sample image that has this problem](https://gist.github.com/mcrawford-fms/da6ff2e277578a24fe11ebeaa0ff46cd)

Reproduction (.Net 6 console app):

``` csharp
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using Svg;

const string inputFile = @"..\..\..\test.svg";
const string outputFile = @"..\..\..\test.jpg";

var svg = SvgDocument.Open(inputFile);
svg.Ppi = 600;

var svgDimensions = svg.GetDimensions();
var bitmapWidth = (int)Math.Round(svgDimensions.Width);
var bitmapHeight = (int)Math.Round(svgDimensions.Height);
using var bitmap = new Bitmap(bitmapWidth, bitmapHeight);
using var graphics = Graphics.FromImage(bitmap);
using var brush = new SolidBrush(Color.White);

graphics.FillRectangle(brush, 0, 0, bitmap.Width, bitmap.Height);
svg.Draw(graphics);
bitmap.Save(outputFile, ImageFormat.Jpeg);
```

#### Used Versions
Svg 3.4.3
Problem occurs with both .Net 6 and Framework 4.6.2

**Comment by H1Gdev** [comment]
@mcrawford-fms 

I am working on fix for this issue, but here is a workaround.

```cs
//svg.Draw(graphics);
svg.Draw(graphics, svgDimensions);
```
