### ISSUE TITLE
Documentation generation is broken

### ISSUE THREAD

**Issue by mrbean-bremen** [svg-net/SVG#1152]
It got broken with the latest commit, and I made it worse by removing the current deployment (which was the recommendation in case of that problem), so there is no documentation at the moment.

Didn't succeed to fix this yet, I will look again tomorrow.

**Comment by mrbean-bremen** [comment]
Update: I succeeded re-generating the documentation for master from another branch, so we at least now have the current documentation online. 
Adding the same changes to master worked, but generated warnings in the documentation build, 
due to a problem with Nerdbank.GitVersioning. The problem is fixed, but I 'll add the callstack leading to the warning in case the problem persists:

<details>
<summary>Relevant Callstack</summary>

```
warning: [Failure] Msbuild failed when processing the file 'D:\a\SVG\SVG\Source\Svg.csproj' with message: C:\Users\runneradmin\.nuget\packages\nerdbank.gitversioning\3.3.37\build\Nerdbank.GitVersioning.Inner.targets: (17, 5): The "Nerdbank.GitVersioning.Tasks.GetBuildVersion" task failed unexpectedly.
System.InvalidOperationException: Unable to get version from commit: d9380e5f38092517e10a90646a653c3779837a3f
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at LibGit2Sharp.Core.Handles.ObjectHandle.op_Implicit(ObjectHandle handle)
   at LibGit2Sharp.Core.Proxy.git_commit_tree_id(ObjectHandle obj)
   at LibGit2Sharp.Commit.<>c__DisplayClass11_0.<.ctor>b__0(ObjectHandle obj)
   at LibGit2Sharp.Core.GitObjectLazyGroup.<>c__DisplayClass3_0`1.<Singleton>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at LibGit2Sharp.Core.LazyGroup`1.LazyWrapper`1.LibGit2Sharp.Core.ILazy<TType>.get_Value()
   at LibGit2Sharp.Commit.get_Tree()
   at Nerdbank.GitVersioning.VersionFile.GetVersion(Commit commit, String repoRelativeProjectDirectory, Dictionary`2 blobVersionCache)
   at Nerdbank.GitVersioning.GitExtensions.GitWalkTracker.GetVersion(Commit commit)
   --- End of inner exception stack trace ---
   at Nerdbank.GitVersioning.GitExtensions.GitWalkTracker.GetVersion(Commit commit)
   at Nerdbank.GitVersioning.GitExtensions.CommitMatchesVersion(Commit commit, SemanticVersion expectedVersion, Position comparisonPrecision, GitWalkTracker tracker)
   at Nerdbank.GitVersioning.GitExtensions.<>c__DisplayClass4_0.<GetVersionHeight>b__0(Commit c)
   at Nerdbank.GitVersioning.GitExtensions.<GetCommitHeight>g__TryCalculateHeight|37_0(Commit commit, <>c__DisplayClass37_0&)
   at Nerdbank.GitVersioning.GitExtensions.GetCommitHeight(Commit startingCommit, GitWalkTracker tracker, Func`2 continueStepping)
   at Nerdbank.GitVersioning.GitExtensions.GetHeight(Commit commit, String repoRelativeProjectDirectory, Func`2 continueStepping)
   at Nerdbank.GitVersioning.GitExtensions.GetVersionHeight(Commit commit, String repoRelativeProjectDirectory, Version baseVersion)
   at Nerdbank.GitVersioning.VersionOracle.CalculateVersionHeight(String relativeRepoProjectDirectory, Commit headCommit, VersionOptions committedVersion, VersionOptions workingVersion)
   at Nerdbank.GitVersioning.VersionOracle..ctor(String projectDirectory, Repository repo, Commit head, ICloudBuild cloudBuild, Nullable`1 overrideVersionHeightOffset, String projectPathRelativeToGitRepoRoot)
   at Nerdbank.GitVersioning.VersionOracle.Create(String projectDirectory, String gitRepoDirectory, ICloudBuild cloudBuild, Nullable`1 overrideBuildNumberOffset, String projectPathRelativeToGitRepoRoot)
   at Nerdbank.GitVersioning.Tasks.GetBuildVersion.ExecuteInner()
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```
</details>
